#cb4ea19816a79290e0f0b102fc285ad57af399547b54ddb91545d8db7ff1b59e2-544e99bf-ab2d-4020-9fc5-4cb736cfff7a00f63473
name: Storybook
on:
  push:
    branches:
      - main # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook
          ng build --output-path docs --base-href /StoryBookTest

      - name: Deploy
        uses: actions/checkout@v3

      - name: Upload to blob storage
        uses: azure/login@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name storybookstg2  --auth-mode key -d '$web' -s .
      
      - name: Purge CDN endpoint
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/docs'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "storybook3" --name "storybook3" --resource-group "StoryBook" 
      
      - name: logout
        run: |
              az logout
        if: always()
        